[package]
name = "genawaiter-try"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-core = { version = "0.3.31", default-features = false }
genawaiter = { version = "0.99.1", features = ["futures03"] }
