name: Publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - run: echo ok
      - name: publish
        run: cargo publish --package genawaiter-try-stream
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: release
        run: |
          curl -sSfL https://github.com/parrrate/ruchei/raw/f96e3cfe35cdec32b6ade70f429d0162f2d953e8/bin/release -o /tmp/gh-release
          chmod +x /tmp/gh-release
          /tmp/gh-release
        env:
          INPUT_TOKEN: ${{ secrets.PUSH_TOKEN }}
